export const VIDEO_STATUS = {
  DRAFT: "DRAFT",
  PLANNING: "PLANNING",
  READY: "READY",
  RENDERING: "RENDERING",
  PROCESSING: "PROCESSING",
  VERIFYING: "VERIFYING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
} as const;

export const SCENE_STATUS = {
  DRAFT: "DRAFT",
  READY: "READY",
  RENDERING: "RENDERING",
  VERIFIED: "VERIFIED",
  FAILED: "FAILED",
} as const;

export const VERIFICATION_STATUS = {
  PENDING: "PENDING",
  PASSED: "PASSED",
  FAILED: "FAILED",
} as const;

export const VIDEO_OBJECT_TYPES = {
  TEXT: "TEXT",
  MODEL: "MODEL",
  IMAGE: "IMAGE",
  PARTICLE: "PARTICLE",
  LIGHT: "LIGHT",
  GROUP: "GROUP",
} as const;

export const ANIMATION_TYPES = {
  APPEAR: "APPEAR",
  DISAPPEAR: "DISAPPEAR",
  MOVE: "MOVE",
  SCALE: "SCALE",
  ROTATE: "ROTATE",
  HIGHLIGHT: "HIGHLIGHT",
  TRANSFORM: "TRANSFORM",
} as const;