export const VERIFICATION_STATUS = {
  VALID: "VALID",
  INVALID: "INVALID",
} as const;

export const VERIFICATION_SEVERITY = {
  ERROR: "ERROR",
  WARNING: "WARNING",
} as const;

export const VERIFICATION_ERROR_CODES = {
  SCENE_GRAPH_REQUIRED:
    "SCENE_GRAPH_REQUIRED",

  SCENE_GRAPH_EMPTY:
    "SCENE_GRAPH_EMPTY",

  MISSING_SCENE_ID:
    "MISSING_SCENE_ID",

  DUPLICATE_SCENE_ID:
    "DUPLICATE_SCENE_ID",

  INVALID_SCENE_ORDER:
    "INVALID_SCENE_ORDER",

  INVALID_SCENE_DURATION:
    "INVALID_SCENE_DURATION",

  MISSING_OBJECT_ID:
    "MISSING_OBJECT_ID",

  DUPLICATE_OBJECT_ID:
    "DUPLICATE_OBJECT_ID",

  INVALID_OBJECT_TYPE:
    "INVALID_OBJECT_TYPE",

  INVALID_OBJECT_TRANSFORM:
    "INVALID_OBJECT_TRANSFORM",

  MISSING_ANIMATION_ID:
    "MISSING_ANIMATION_ID",

  DUPLICATE_ANIMATION_ID:
    "DUPLICATE_ANIMATION_ID",

  UNKNOWN_ANIMATION_OBJECT:
    "UNKNOWN_ANIMATION_OBJECT",

  INVALID_ANIMATION_TYPE:
    "INVALID_ANIMATION_TYPE",

  INVALID_ANIMATION_START_TIME:
    "INVALID_ANIMATION_START_TIME",

  INVALID_ANIMATION_DURATION:
    "INVALID_ANIMATION_DURATION",

  ANIMATION_OUT_OF_BOUNDS:
    "ANIMATION_OUT_OF_BOUNDS",

  MISSING_CAMERA:
    "MISSING_CAMERA",

  INVALID_CAMERA_TRANSFORM:
    "INVALID_CAMERA_TRANSFORM",

  INVALID_CAMERA_FOV:
    "INVALID_CAMERA_FOV",

  INVALID_NARRATION_TEXT:
    "INVALID_NARRATION_TEXT",

  INVALID_NARRATION_START_TIME:
    "INVALID_NARRATION_START_TIME",

  INVALID_NARRATION_DURATION:
    "INVALID_NARRATION_DURATION",

  NARRATION_OUT_OF_BOUNDS:
    "NARRATION_OUT_OF_BOUNDS",
} as const;

export type VerificationErrorCode =
  (typeof VERIFICATION_ERROR_CODES)[keyof typeof VERIFICATION_ERROR_CODES];